"""empty message

Revision ID: 556a28bb7b90
Revises: 5eddf1e8f396
Create Date: 2023-05-07 22:35:43.801580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '556a28bb7b90'
down_revision = '5eddf1e8f396'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
